// 3D weapon viewer — efficiency-first design:
// - three.js is DYNAMICALLY imported (own chunk, fetched only on first 3D use)
// - model availability is a cached HEAD check (no model file → silent 2D fallback)
// - parsed GLTFs live in a small LRU cache; only ONE live viewer exists at a
//   time (the Focus view), so a fresh lightweight renderer per mount is cheaper
//   than keeping a GL context alive globally. Snapshot-to-image for grid cards
//   (shared offscreen renderer + IndexedDB cache) is phase 2.
//
// Stickers render as surface-projected decals (three's DecalGeometry) and are
// DRAGGABLE in interactive mode — positions round-trip through the game's own
// sticker-offset space (cs2-lib per-weapon bounds). The charm is a verlet
// pendulum hanging off the body: it sways idly, reacts to placement changes,
// and can be grabbed/flung with the pointer.
//
// Skin rendering is a faithful port of CS2's compositing pipeline — see
// paintComposite.ts for the shader and its provenance.
import { API_ORIGIN } from "./api";
import { compositePaint, dropCompositeCache, loadPaintDef, loadWeaponInputs, paintTextureUrl } from "./paintComposite";
// Per-weapon charm anchors, generated by scripts/extract-models.sh §3c from the
// weapon models' own `keychain` attachment. Regenerate on a CS2 update rather
// than hand-editing — the values are exact, not tuned.
import CHARM_ANCHORS from "./charmAnchors.json";
import { createViewerCursor, type CursorMode } from "./viewerCursor";

export { loadPaintDef, type PaintDef } from "./paintComposite";

type ThreeBundle = {
  THREE: typeof import("three");
  GLTFLoader: typeof import("three/examples/jsm/loaders/GLTFLoader.js").GLTFLoader;
  OrbitControls: typeof import("three/examples/jsm/controls/OrbitControls.js").OrbitControls;
  DecalGeometry: typeof import("three/examples/jsm/geometries/DecalGeometry.js").DecalGeometry;
  RoomEnvironment: typeof import("three/examples/jsm/environments/RoomEnvironment.js").RoomEnvironment;
};

let threePromise: Promise<ThreeBundle> | null = null;
function loadThree(): Promise<ThreeBundle> {
  threePromise ??= Promise.all([
    import("three"),
    import("three/examples/jsm/loaders/GLTFLoader.js"),
    import("three/examples/jsm/controls/OrbitControls.js"),
    import("three/examples/jsm/geometries/DecalGeometry.js"),
    import("three/examples/jsm/environments/RoomEnvironment.js"),
  ]).then(([THREE, gltf, orbit, decal, env]) => ({
    THREE,
    GLTFLoader: gltf.GLTFLoader,
    OrbitControls: orbit.OrbitControls,
    DecalGeometry: decal.DecalGeometry,
    RoomEnvironment: env.RoomEnvironment,
  }));
  return threePromise;
}

export const modelUrlFor = (model: string) => `${API_ORIGIN}/models/${encodeURIComponent(model)}.glb`;

// HEAD-check whether a .glb exists for this weapon model; results are cached
// for the session so grids/toggles can query freely.
const availability = new Map<string, Promise<boolean>>();
export function hasModel(model: string): Promise<boolean> {
  let cached = availability.get(model);
  if (!cached) {
    cached = fetch(modelUrlFor(model), { method: "HEAD" })
      .then((res) => res.ok && !(res.headers.get("content-type") ?? "").includes("text/html"))
      .catch(() => false);
    availability.set(model, cached);
  }
  return cached;
}

// Parsed-GLTF LRU (the heavy part — geometry + textures).
const gltfCache = new Map<string, Promise<import("three/examples/jsm/loaders/GLTFLoader.js").GLTF>>();
const GLTF_CACHE_MAX = 8;
async function loadGltf(model: string) {
  const existing = gltfCache.get(model);
  if (existing) {
    // refresh LRU order
    gltfCache.delete(model);
    gltfCache.set(model, existing);
    return existing;
  }
  const { GLTFLoader } = await loadThree();
  const entry = new GLTFLoader().loadAsync(modelUrlFor(model));
  gltfCache.set(model, entry);
  if (gltfCache.size > GLTF_CACHE_MAX) {
    const oldest = gltfCache.keys().next().value;
    if (oldest) gltfCache.delete(oldest);
  }
  return entry;
}

// Shared texture cache (sticker/charm images are tiny and reused across
// viewer mounts — never disposed with a viewer).
const texCache = new Map<string, Promise<import("three").Texture>>();
async function loadTexture(url: string) {
  let cached = texCache.get(url);
  if (!cached) {
    cached = loadThree().then(async ({ THREE }) => {
      const tex = await new THREE.TextureLoader().loadAsync(url);
      tex.colorSpace = THREE.SRGBColorSpace;
      return tex;
    });
    texCache.set(url, cached);
  }
  return cached;
}

// Charm art ships with generous transparent padding — hanging the raw quad by
// its top edge leaves the charm floating in air below its anchor. Crop each
// image to its alpha bounding box once (cached) so the art's own connector
// sits flush against the attachment point.
const charmTexCache = new Map<string, Promise<{ tex: import("three").Texture; aspect: number } | null>>();
function loadCharmTexture(url: string) {
  let cached = charmTexCache.get(url);
  if (!cached) {
    cached = (async () => {
      try {
        const { THREE } = await loadThree();
        const img = await loadBitmap(url);
        const cv = document.createElement("canvas");
        cv.width = img.width;
        cv.height = img.height;
        const ctx = cv.getContext("2d", { willReadFrequently: true })!;
        ctx.drawImage(img, 0, 0);
        const d = ctx.getImageData(0, 0, cv.width, cv.height).data;
        let minX = cv.width;
        let minY = cv.height;
        let maxX = -1;
        let maxY = -1;
        for (let y = 0; y < cv.height; y++) {
          for (let x = 0; x < cv.width; x++) {
            // > 48: faint halo/shadow pixels above the art used to stretch the
            // bbox, leaving a visual gap between the cord and the charm.
            if (d[(y * cv.width + x) * 4 + 3] > 48) {
              if (x < minX) minX = x;
              if (x > maxX) maxX = x;
              if (y < minY) minY = y;
              if (y > maxY) maxY = y;
            }
          }
        }
        if (maxX < 0) {
          minX = minY = 0;
          maxX = cv.width - 1;
          maxY = cv.height - 1;
        }
        const w = maxX - minX + 1;
        const h = maxY - minY + 1;
        const crop = document.createElement("canvas");
        crop.width = w;
        crop.height = h;
        crop.getContext("2d")!.drawImage(cv, minX, minY, w, h, 0, 0, w, h);
        const tex = new THREE.CanvasTexture(crop);
        tex.colorSpace = THREE.SRGBColorSpace;
        return { tex, aspect: w / h };
      } catch {
        return null;
      }
    })();
    charmTexCache.set(url, cached);
  }
  return cached;
}

async function loadBitmap(url: string): Promise<ImageBitmap> {
  const res = await fetch(url);
  return createImageBitmap(await res.blob());
}

// ---- Sticker / charm placement ------------------------------------------------
export interface StickerPlacement {
  slot: number; // 0..4
  image: string;
  x: number | null; // game sticker-offset units (cs2-lib bounds space)
  y: number | null;
  r: number | null; // degrees
  w: number | null; // scratch wear, 0 pristine .. 1 scratched off
}
export interface CharmPlacement {
  image: string;
  x: number | null; // normalized [-1,1] along the body
  y: number | null;
  z: number | null;
}
export interface StickerSlot {
  index: number;
  mesh: string;
  offset: [number, number];
  scale: number;
  rotation: number;
  special?: string;
}
export interface StickerBounds {
  x: [number, number];
  y: [number, number];
}
// Fallback when a weapon has no bounds in cs2-lib (rough AK-like envelope).
const DEFAULT_BOUNDS: StickerBounds = { x: [-0.4, 0.66], y: [-0.08, 0.24] };
const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, v));
const round = (v: number, p: number) => Number(v.toFixed(p));

// Crop a snapshot PNG to its visible content (+small margin). The raw frame
// is 640x480 with large transparent borders — next to tightly-cropped catalog
// art the gun looked shrunken inside identical <img> boxes.
//
// Aspect cap: cards fit these with object-contain, so a crop much wider than
// its box goes full-bleed while normal crops stop at the height cap — the gun
// in the slim crop draws ~25% longer than its neighbors. Long guns cluster at
// ~3.2-3.5; only near-horizontal poses (the Nova) land way above. Padding those
// back down to the cluster keeps every gun at the same on-screen scale.
const MAX_CROP_ASPECT = 3.6;
async function cropToContent(blob: Blob, margin = 0.03): Promise<Blob | null> {
  try {
    const img = await createImageBitmap(blob);
    const cv = document.createElement("canvas");
    cv.width = img.width;
    cv.height = img.height;
    const ctx = cv.getContext("2d", { willReadFrequently: true })!;
    ctx.drawImage(img, 0, 0);
    const d = ctx.getImageData(0, 0, cv.width, cv.height).data;
    let minX = cv.width;
    let minY = cv.height;
    let maxX = -1;
    let maxY = -1;
    for (let y = 0; y < cv.height; y++) {
      for (let x = 0; x < cv.width; x++) {
        if (d[(y * cv.width + x) * 4 + 3] > 8) {
          if (x < minX) minX = x;
          if (x > maxX) maxX = x;
          if (y < minY) minY = y;
          if (y > maxY) maxY = y;
        }
      }
    }
    if (maxX < 0) return blob; // fully transparent — keep as-is
    const mx = Math.round((maxX - minX + 1) * margin);
    const my = Math.round((maxY - minY + 1) * margin);
    minX = Math.max(0, minX - mx);
    minY = Math.max(0, minY - my);
    maxX = Math.min(cv.width - 1, maxX + mx);
    maxY = Math.min(cv.height - 1, maxY + my);
    const w = maxX - minX + 1;
    const h = maxY - minY + 1;
    const padY = w / h > MAX_CROP_ASPECT ? Math.ceil((w / MAX_CROP_ASPECT - h) / 2) : 0;
    const out = document.createElement("canvas");
    out.width = w;
    out.height = h + padY * 2;
    out.getContext("2d")!.drawImage(cv, minX, minY, w, h, 0, padY, w, h);
    return await new Promise<Blob | null>((resolve) => out.toBlob(resolve, "image/png"));
  } catch {
    return blob;
  }
}

// One-shot offscreen snapshot: mounts the REAL viewer (paint, wear, seed,
// sticker decals, charm) in a hidden container, lets attachments settle,
// grabs a frame, crops it to the content, and tears down. Cards get exactly
// what the 3D view shows, framed as tight as catalog art.
// Every snapshot burns a WebGL context for ~1s. Callers arrive from independent
// paths (the bake queue, the craft preview's debounced watch) that don't know
// about each other, so a wear/seed slider drag used to stack overlapping
// contexts until mobile Safari hit its cap and started killing them. One global
// lane means the offscreen cost is exactly one context no matter who asks.
let snapshotLane: Promise<unknown> = Promise.resolve();
export function snapshotModel(
  model: string,
  opts: Omit<ViewerOpts, "interactive" | "still">,
  /** Checked once the lane frees up — return false if this result is already
   *  stale (e.g. the user kept dragging the wear slider) to skip the work. */
  stillWanted?: () => boolean,
): Promise<Blob | null> {
  const run = snapshotLane.then(() => (stillWanted && !stillWanted() ? null : snapshotModelNow(model, opts)));
  snapshotLane = run.catch(() => null);
  return run;
}

async function snapshotModelNow(model: string, opts: Omit<ViewerOpts, "interactive" | "still">): Promise<Blob | null> {
  const holder = document.createElement("div");
  holder.style.cssText = "position:fixed;left:-10000px;top:0;width:640px;height:480px;pointer-events:none;";
  document.body.appendChild(holder);
  let handle: ViewerHandle | null = null;
  try {
    handle = await mountViewer(holder, model, { ...opts, interactive: false, still: true, frame: "fit" });
    // Decal texture loads + a few physics frames for the charm to hang.
    await new Promise((r) => setTimeout(r, 750));
    const raw = await handle.snapshot();
    return raw ? await cropToContent(raw) : raw;
  } catch {
    return null;
  } finally {
    handle?.dispose();
    holder.remove();
  }
}

export interface ViewerHandle {
  dispose: () => void;
  setStickers: (stickers: StickerPlacement[]) => void;
  /** Pulse a decal so the user can find it — no effect on the saved placement. */
  flashSticker: (slot: number) => void;
  setCharm: (charm: CharmPlacement | null) => void;
  snapshot: () => Promise<Blob | null>;
}

export interface ViewerOpts {
  paintMaterial?: string | null;
  // Pre-CS2 finish → render the legacy body (its UV unwrap is what the
  // pattern was authored against). CS2-native finishes use the HD body.
  legacyPaint?: boolean;
  wear?: number | null;
  seed?: number | null;
  still?: boolean; // no auto-rotate (snapshots)
  frame?: number | "fit"; // distance multiplier, or "fit" = largest no-clip framing
  stickers?: StickerPlacement[];
  charm?: CharmPlacement | null;
  stickerBounds?: StickerBounds | null;
  /** Per-slot UV anchors from the model. Without them placement falls back to
   *  the old silhouette guess, which does NOT match the game. */
  stickerSlots?: StickerSlot[];
  // Interactive placement: drag stickers across the surface, grab the charm.
  interactive?: boolean;
  onStickerPlaced?: (slot: number, x: number, y: number) => void;
  /** Shift-drag on a sticker — degrees, 0-360. */
  onStickerRotated?: (slot: number, r: number) => void;
  onCharmPlaced?: (x: number, y: number, z: number) => void;
  /** The GPU dropped this viewer's context. The handle is dead — remount to recover. */
  onContextLost?: () => void;
  /**
   * Lighting overrides, for calibrating against reference renders with
   * tools/shadertest. Production never passes these — the defaults below are
   * the calibrated values. Exposed so exposure/contrast can be swept and
   * MEASURED rather than eyeballed, which is how the last two rounds of
   * "it looks washed out" went wrong.
   */
  lighting?: { env?: number; key?: number; rim?: number; ambient?: number };
}

// Mount an interactive orbit viewer into `container`. Returns a handle whose
// dispose() MUST be called on unmount/model switch.
export async function mountViewer(
  container: HTMLElement,
  model: string,
  opts?: ViewerOpts,
): Promise<ViewerHandle> {
  const { THREE, OrbitControls, DecalGeometry, RoomEnvironment } = await loadThree();
  // Which body survived the hd/legacy prune below — slot markup is per-variant.
  let bodyVariant = "body_hd";
  const gltf = await loadGltf(model);

  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.outputColorSpace = THREE.SRGBColorSpace;
  // Khronos PBR-neutral: color-accurate product rendering (ACES pushes
  // saturated skin colors toward orange/teal — wrong for a skin inspector).
  renderer.toneMapping = THREE.NeutralToneMapping;
  renderer.toneMappingExposure = 1.0;
  renderer.domElement.style.width = "100%";
  renderer.domElement.style.height = "100%";
  renderer.domElement.style.display = "block";
  renderer.domElement.style.touchAction = "none";
  // A long-press drag (charms/stickers on touch) must never start OS text
  // selection or iOS Live Text on the canvas — that pops the Copy / Look Up /
  // Translate callout mid-drag. Cover the container too so the selection
  // can't seed from text right at the canvas edge.
  for (const target of [renderer.domElement, container]) {
    target.style.userSelect = "none";
    target.style.setProperty("-webkit-user-select", "none");
    target.style.setProperty("-webkit-touch-callout", "none");
  }
  container.appendChild(renderer.domElement);

  const scene = new THREE.Scene();
  // Image-based studio lighting carries the shading (composited metal/rough
  // maps need real reflections); directionals only shape highlights. Ambient
  // stays tiny — stacking it on IBL flattens the PBR response.
  const pmrem = new THREE.PMREMGenerator(renderer);
  const envTex = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
  pmrem.dispose();
  scene.environment = envTex;
  // Calibrated against the official CDN renders with tools/shadertest.
  //
  // History worth keeping, because it is a trap: these were first cut ~1.8x to
  // chase a washed-out render. That wash was NOT lighting — it was the palette
  // being read as linear when the compiled vmat stores sRGB, which made every
  // colour pale and grey. Fixing the palette left the scene under-lit, since the
  // cut had been calibrated against corrupted numbers. Do not tune this rig by
  // eye against a suspected shader bug; fix the data first, then calibrate.
  //
  // Calibration targets, captured with runViewer() and compared to the official
  // CDN renders:
  //   AK-47 | Safari Mesh @0.265  reference (109,105,80) sat 29.9
  //   FAMAS | Byproduct   @0.408  reference (109,101,79) sat 30.6
  const L = opts?.lighting ?? {};
  scene.environmentIntensity = L.env ?? 1.05;
  scene.add(new THREE.AmbientLight(0xffffff, L.ambient ?? 0.12));
  const key = new THREE.DirectionalLight(0xffffff, L.key ?? 1.15);
  key.position.set(2, 3, 4);
  scene.add(key);
  const rim = new THREE.DirectionalLight(0xdde6ff, L.rim ?? 0.35);
  rim.position.set(-3, 1, -2);
  scene.add(rim);

  // Clone so cached GLTF scenes are never mutated by a live viewer.
  const object = gltf.scene.clone(true);
  // CS2 exports ship BOTH bodies stacked: the CS:GO-era "_legacy" mesh AND the
  // CS2 "_hd" mesh. They are different geometry with DIFFERENT UV unwraps —
  // and paints target a specific one: pre-CS2 finishes (cs2-lib `legacy`) are
  // authored against the legacy body's unwrap, CS2-native finishes against
  // the HD body's. Rendering the wrong body scatters the pattern into
  // patchwork; rendering both z-fights. Keep exactly the body the equipped
  // finish targets (HD when unpainted).
  {
    let hasHd = false;
    let hasLegacy = false;
    object.traverse((node) => {
      const n = node.name ?? "";
      if (/(_hd|\.hd)\b/i.test(n)) hasHd = true;
      if (/_legacy/i.test(n)) hasLegacy = true;
    });
    if (hasHd && hasLegacy) {
      const useLegacy = !!opts?.legacyPaint && !!opts?.paintMaterial;
      bodyVariant = useLegacy ? "body_legacy" : "body_hd";
      const dropPattern = useLegacy ? /(_hd|\.hd)\b/i : /_legacy/i;
      const drop: import("three").Object3D[] = [];
      object.traverse((node) => {
        if (dropPattern.test(node.name ?? "")) drop.push(node);
      });
      drop.forEach((nodeToRemove) => nodeToRemove.parent?.remove(nodeToRemove));
    }
  }
  // The sticker_gaps strips carry their own tiny texture — never paint them.
  const isGapMesh = (mesh: import("three").Mesh) => {
    const m = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material;
    return /sticker_gaps/i.test((m as import("three").Material)?.name ?? "");
  };
  scene.add(object);

  // Apply the equipped skin through the ported CS2 compositor (see
  // paintComposite.ts): Valve-exact wear/grunge/style math rendered into
  // albedo + rough/metal maps in the body's paint UV space (TEXCOORD_0 — the
  // same set the weapon material's own textures use; TEXCOORD_1 is stickers).
  // Worn areas reveal the weapon base color exactly like the game.
  let releaseComposite: (() => void) | null = null;
  if (opts?.paintMaterial) {
    try {
      const [paint, weaponInputs] = await Promise.all([
        loadPaintDef(opts.paintMaterial),
        // Must match the body chosen below (bodyVariant): the legacy and HD
        // composite-input sets are authored against different unwraps.
        loadWeaponInputs(model, !!opts?.legacyPaint),
      ]);
      if (paint) {
        const comp = await compositePaint(THREE, renderer, paint, {
          wear: opts?.wear ?? 0,
          seed: opts?.seed ?? 0,
          weapon: weaponInputs,
          model, // so a fallback can be reported against the weapon it broke
        });
        // Custom paint jobs ship their own normal map (paint-UV space).
        const normalTex = paint.normal
          ? await new THREE.TextureLoader()
              .loadAsync(await paintTextureUrl(paint.normal))
              .then((t) => {
                t.flipY = false;
                t.channel = 0; // paint UV = the weapon material's own uv set
                t.wrapS = t.wrapT = THREE.RepeatWrapping;
                t.anisotropy = Math.min(8, renderer.capabilities.getMaxAnisotropy());
                return t;
              })
              .catch(() => null)
          : null;
        if (comp) {
          releaseComposite = comp.release;
          object.traverse((node) => {
            const mesh = node as import("three").Mesh;
            if (!(mesh as unknown as { isMesh?: boolean }).isMesh || isGapMesh(mesh)) return;
            const source = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
            const painted = source.map((m) => {
              const mat = (m as import("three").MeshStandardMaterial).clone();
              mat.map = comp.albedo;
              mat.color?.set(0xffffff);
              mat.roughnessMap = comp.rm; // G channel
              mat.roughness = 1;
              mat.metalnessMap = comp.rm; // B channel
              mat.metalness = 1;
              if (normalTex) mat.normalMap = normalTex;
              mat.needsUpdate = true;
              return mat;
            });
            mesh.material = Array.isArray(mesh.material) ? painted : painted[0];
          });
        }
      }
    } catch {
      /* paint failed to load — untextured model still renders */
    }
  }

  // Auto-frame: center the model and pull the camera back to fit.
  const box = new THREE.Box3().setFromObject(object);
  const size = box.getSize(new THREE.Vector3());
  const center = box.getCenter(new THREE.Vector3());
  object.position.sub(center);
  object.updateMatrixWorld(true);
  const radius = Math.max(size.x, size.y, size.z) || 1;
  const cboxFit = new THREE.Box3().setFromObject(object);

  const camera = new THREE.PerspectiveCamera(35, 1, radius / 100, radius * 100);
  if (opts?.frame === "fit") {
    // Exact-fit: solve the minimum camera distance where every bbox corner is
    // inside the frustum, then add a small margin. Max gun, zero edge-clip.
    const aspect = (container.clientWidth || 640) / (container.clientHeight || 480);
    const tanV = Math.tan((35 * Math.PI) / 360);
    const tanH = tanV * aspect;
    const dir = new THREE.Vector3(1.4, 0.35, 1.1).normalize();
    const right = new THREE.Vector3().crossVectors(new THREE.Vector3(0, 1, 0), dir).normalize();
    const upv = new THREE.Vector3().crossVectors(dir, right);
    let dist = 0;
    for (const cx of [cboxFit.min.x, cboxFit.max.x])
      for (const cy of [cboxFit.min.y, cboxFit.max.y])
        for (const cz of [cboxFit.min.z, cboxFit.max.z]) {
          const c = new THREE.Vector3(cx, cy, cz);
          const depth = c.dot(dir);
          dist = Math.max(dist, depth + Math.abs(c.dot(right)) / tanH, depth + Math.abs(c.dot(upv)) / tanV);
        }
    camera.position.copy(dir.multiplyScalar(dist * 1.07));
  } else {
    const frame = opts?.frame ?? 1;
    camera.position.set(radius * 1.4 * frame, radius * 0.35 * frame, radius * 1.1 * frame);
  }

  const controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  // Spinning while trying to drag a sticker is misery — static in editors.
  controls.autoRotate = !opts?.interactive && !opts?.still;
  controls.autoRotateSpeed = 0.9;
  // Pan (right-drag / two-finger drag) + a closer zoom floor: precision work
  // on touch is done by zooming INTO the spot and panning it under your
  // finger, not by aiming a 1:1 drag across the whole weapon.
  controls.enablePan = true;
  controls.screenSpacePanning = true;
  controls.minDistance = radius * 0.22;
  controls.maxDistance = radius * 4;
  // Coarse pointers get a slower orbit — a thumb sweep is far larger than a
  // mouse gesture, so 1:1 rotate speed makes small adjustments overshoot.
  if (typeof matchMedia !== "undefined" && matchMedia("(pointer: coarse)").matches) controls.rotateSpeed = 0.6;
  // Keep the pan on a leash: clamp the orbit target to the model's own bounds
  // so the weapon can never be flung off-screen with no way back.
  controls.addEventListener("change", () => {
    controls.target.x = clamp(controls.target.x, -radius, radius);
    controls.target.y = clamp(controls.target.y, -radius, radius);
    controls.target.z = clamp(controls.target.z, -radius, radius);
  });

  // ---- Placement space ---------------------------------------------------------
  // Weapons lie along their longest axis; height is Y unless Y IS the length.
  // Sticker offsets from the game map linearly onto (length, height) with one
  // scale constant, clamped to the weapon's cs2-lib bounds.
  const cbox = new THREE.Box3().setFromObject(object); // recomputed after centering
  const dims = [size.x, size.y, size.z];
  const AXIS_L = dims.indexOf(Math.max(...dims));
  const AXIS_H = AXIS_L === 1 ? (size.x >= size.z ? 0 : 2) : 1;
  const AXIS_S = 3 - AXIS_L - AXIS_H;
  const sizeL = dims[AXIS_L];
  const sizeH = dims[AXIS_H];
  const sizeS = dims[AXIS_S];
  const bounds = opts?.stickerBounds ?? DEFAULT_BOUNDS;
  const OFFSET_SCALE = sizeL * 0.55; // world units per game offset unit
  const baseH = (cbox.min.getComponent(AXIS_H) + cbox.max.getComponent(AXIS_H)) / 2;
  const centerS = (cbox.min.getComponent(AXIS_S) + cbox.max.getComponent(AXIS_S)) / 2;

  const weaponMeshes: import("three").Mesh[] = [];
  object.traverse((node) => {
    const mesh = node as import("three").Mesh;
    if ((mesh as unknown as { isMesh?: boolean }).isMesh && !isGapMesh(mesh)) weaponMeshes.push(mesh);
  });

  const raycaster = new THREE.Raycaster();
  // Cast toward the body at (length, height), from the near side then the far
  // side, and return the surface point + world normal to project a decal onto.
  // `only` restricts the probe to one side — used to measure body thickness.
  function castAt(l: number, h: number, only?: 1 | -1) {
    for (const sign of only ? [only] : [1, -1]) {
      const origin = new THREE.Vector3();
      origin.setComponent(AXIS_L, l);
      origin.setComponent(AXIS_H, h);
      origin.setComponent(AXIS_S, centerS + sign * sizeS * 2);
      const dir = new THREE.Vector3();
      dir.setComponent(AXIS_S, -sign);
      raycaster.set(origin, dir);
      const hit = raycaster.intersectObjects(weaponMeshes, false)[0];
      if (hit?.face) {
        const normal = hit.face.normal.clone().transformDirection(hit.object.matrixWorld);
        return { mesh: hit.object as import("three").Mesh, point: hit.point, normal };
      }
    }
    return null;
  }

  // Where do stickers with no offset go? A fixed fraction of the length doesn't
  // work: on a suppressed rifle the front third is barrel, so a fresh sticker
  // landed on a thin cylinder and got culled away as glancing geometry — you
  // added it and saw nothing. Instead probe the silhouette for the *body*: walk
  // the length measuring near-to-far thickness, then keep the longest run that
  // is at least half as thick as the thickest point. That's the receiver /
  // magazine block on every weapon, whichever way the model faces, and it's
  // where CS2 puts stickers too.
  function bodySpanL(): [number, number] {
    const lo = cbox.min.getComponent(AXIS_L);
    const span = sizeL;
    const STEPS = 48;
    const thickness: number[] = [];
    for (let i = 0; i < STEPS; i++) {
      const l = lo + ((i + 0.5) / STEPS) * span;
      const near = castAt(l, baseH, 1);
      const far = castAt(l, baseH, -1);
      thickness.push(
        near && far ? Math.abs(near.point.getComponent(AXIS_S) - far.point.getComponent(AXIS_S)) : 0,
      );
    }
    const max = Math.max(...thickness);
    if (max <= 0) return [lo + 0.28 * span, lo + 0.72 * span]; // no hits — old behaviour
    const min = max * 0.5;
    let best: [number, number] = [0, -1];
    let start = -1;
    for (let i = 0; i <= STEPS; i++) {
      const solid = i < STEPS && thickness[i] >= min;
      if (solid && start < 0) start = i;
      if (!solid && start >= 0) {
        if (i - 1 - start > best[1] - best[0]) best = [start, i - 1];
        start = -1;
      }
    }
    if (best[1] < best[0]) return [lo + 0.28 * span, lo + 0.72 * span];
    return [lo + ((best[0] + 0.5) / STEPS) * span, lo + ((best[1] + 0.5) / STEPS) * span];
  }
  const [bodyL0, bodyL1] = bodySpanL();
  // Inset so slot 0 and slot 4 don't hang off the ends of the body, then space
  // the five slots evenly across what's left.
  const slotBaseL = (slot: number) => {
    const inset = (bodyL1 - bodyL0) * 0.12;
    const a = bodyL0 + inset;
    const b = bodyL1 - inset;
    return a + ((b - a) * Math.min(4, Math.max(0, slot))) / 4;
  };

  // ---- UV1 -> surface -----------------------------------------------------------
  // CS2 anchors stickers in TEXCOORD_1 space, not in world space, so a slot's
  // position is a UV coordinate that has to be resolved back onto the mesh.
  // Walk the triangles, find the one whose UV1 triangle contains the point, and
  // barycentrically interpolate position + normal. Linear, but it runs once per
  // placement change on ~13k triangles, which is nothing next to a decal build.
  function uv1ToSurface(u: number, v: number) {
    for (const mesh of weaponMeshes) {
      const geom = mesh.geometry as import("three").BufferGeometry;
      const uvAttr = geom.getAttribute("uv1") ?? geom.getAttribute("uv2");
      const posAttr = geom.getAttribute("position");
      const nrmAttr = geom.getAttribute("normal");
      if (!uvAttr || !posAttr) continue;
      const idx = geom.getIndex();
      const triCount = idx ? idx.count / 3 : posAttr.count / 3;
      for (let t = 0; t < triCount; t++) {
        const a = idx ? idx.getX(t * 3) : t * 3;
        const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1;
        const c = idx ? idx.getX(t * 3 + 2) : t * 3 + 2;
        const ax = uvAttr.getX(a), ay = uvAttr.getY(a);
        const bx = uvAttr.getX(b), by = uvAttr.getY(b);
        const cx = uvAttr.getX(c), cy = uvAttr.getY(c);
        // Barycentric in UV space; the same weights carry over to position.
        const d = (by - cy) * (ax - cx) + (cx - bx) * (ay - cy);
        if (Math.abs(d) < 1e-12) continue;
        const w0 = ((by - cy) * (u - cx) + (cx - bx) * (v - cy)) / d;
        const w1 = ((cy - ay) * (u - cx) + (ax - cx) * (v - cy)) / d;
        const w2 = 1 - w0 - w1;
        if (w0 < -1e-6 || w1 < -1e-6 || w2 < -1e-6) continue;
        const point = new THREE.Vector3();
        const tmp = new THREE.Vector3();
        point.addScaledVector(tmp.fromBufferAttribute(posAttr, a), w0);
        point.addScaledVector(tmp.fromBufferAttribute(posAttr, b), w1);
        point.addScaledVector(tmp.fromBufferAttribute(posAttr, c), w2);
        mesh.localToWorld(point);
        const normal = new THREE.Vector3();
        if (nrmAttr) {
          normal.addScaledVector(tmp.fromBufferAttribute(nrmAttr, a), w0);
          normal.addScaledVector(tmp.fromBufferAttribute(nrmAttr, b), w1);
          normal.addScaledVector(tmp.fromBufferAttribute(nrmAttr, c), w2);
          normal.transformDirection(mesh.matrixWorld).normalize();
        }
        return { mesh, point, normal: normal.lengthSq() ? normal : new THREE.Vector3(0, 1, 0) };
      }
    }
    return null;
  }

  // TEXCOORD_1 at a raycast hit — the inverse of uv1ToSurface, used to turn a
  // pointer position back into the offsets the game consumes.
  function surfaceUv1(hit: import("three").Intersection) {
    const mesh = hit.object as import("three").Mesh;
    const geom = mesh.geometry as import("three").BufferGeometry | undefined;
    const uvAttr = geom?.getAttribute("uv1") ?? geom?.getAttribute("uv2");
    if (!geom || !uvAttr || hit.face == null) return null;
    const { a, b, c } = hit.face;
    const pos = geom.getAttribute("position");
    const tri = new THREE.Triangle(
      new THREE.Vector3().fromBufferAttribute(pos, a),
      new THREE.Vector3().fromBufferAttribute(pos, b),
      new THREE.Vector3().fromBufferAttribute(pos, c),
    );
    const local = mesh.worldToLocal(hit.point.clone());
    const bary = new THREE.Vector3();
    tri.getBarycoord(local, bary);
    return {
      u: uvAttr.getX(a) * bary.x + uvAttr.getX(b) * bary.y + uvAttr.getX(c) * bary.z,
      v: uvAttr.getY(a) * bary.x + uvAttr.getY(b) * bary.y + uvAttr.getY(c) * bary.z,
    };
  }

  // A slot's UV anchor plus the user's offset, in the game's own space.
  // uv1 = slotOffset + userOffset + 0.5 (the shader declares the offset range
  // as Range2(-0.5,-0.5, 0.5,0.5), i.e. UV recentred on 0.5).
  const slotMarkup = (slot: number) =>
    (opts?.stickerSlots ?? []).find((sm) => sm.index === slot && sm.mesh === bodyVariant) ??
    (opts?.stickerSlots ?? []).find((sm) => sm.index === slot);

  // ---- Sticker decals ----------------------------------------------------------
  // How many world units one TEXCOORD_1 unit spans, taken as the median over
  // triangle edges (median, not mean: degenerate slivers would drag an average
  // anywhere). A sticker covers 1/Scale UV units, so its world size is
  // density/Scale — which lands at the ~2.9in real stickers measure, where the
  // old `sizeL * 0.11` constant made them ~45% too big on an AK.
  const uv1Density = (() => {
    const ratios: number[] = [];
    for (const mesh of weaponMeshes) {
      const geom = mesh.geometry as import("three").BufferGeometry;
      const uvAttr = geom.getAttribute("uv1") ?? geom.getAttribute("uv2");
      const posAttr = geom.getAttribute("position");
      if (!uvAttr || !posAttr) continue;
      const idx = geom.getIndex();
      const triCount = idx ? idx.count / 3 : posAttr.count / 3;
      const wa = new THREE.Vector3();
      const wb = new THREE.Vector3();
      for (let t = 0; t < triCount; t++) {
        const a = idx ? idx.getX(t * 3) : t * 3;
        const b = idx ? idx.getX(t * 3 + 1) : t * 3 + 1;
        wa.fromBufferAttribute(posAttr, a);
        wb.fromBufferAttribute(posAttr, b);
        mesh.localToWorld(wa);
        mesh.localToWorld(wb);
        const wl = wa.distanceTo(wb);
        const ul = Math.hypot(uvAttr.getX(a) - uvAttr.getX(b), uvAttr.getY(a) - uvAttr.getY(b));
        if (ul > 1e-5 && wl > 1e-6) ratios.push(wl / ul);
      }
    }
    if (!ratios.length) return null;
    ratios.sort((x, y) => x - y);
    return ratios[Math.floor(ratios.length / 2)];
  })();
  // Fallback only — a guess, and it looks like one next to the real thing.
  const DECAL_SIZE = sizeL * 0.11;
  const decalSizeFor = (slot: number) => {
    const mk = slotMarkup(slot);
    return mk && uv1Density && mk.scale > 0 ? uv1Density / mk.scale : DECAL_SIZE;
  };
  type DecalEntry = { key: string; seq: number };
  const decals = new Map<number, DecalEntry>();
  // Rendered decal meshes live in a separate registry: async builds supersede
  // each other via `decals`, but the on-screen mesh must be disposed exactly
  // once regardless of how many in-flight builds got aborted.
  const liveMesh = new Map<number, import("three").Mesh>();
  let decalSeq = 0;
  let disposed = false;

  function disposeSlotMesh(slot: number) {
    const m = liveMesh.get(slot);
    if (m) {
      scene.remove(m);
      m.geometry.dispose();
      (m.material as import("three").Material).dispose();
      liveMesh.delete(slot);
    }
    // A flash outlives its mesh otherwise, and would then re-target whatever
    // mesh next lands in this slot.
    flashing.delete(slot);
  }
  function removeDecal(slot: number) {
    disposeSlotMesh(slot);
    decals.delete(slot);
  }

  // DecalGeometry clips triangles to the projection box with NO facing check:
  // geometry nearly parallel to the projection (rail teeth, sight posts, mag
  // edges) gets clamped edge texels smeared across it — the "film over the
  // rail" artifact. Keep only faces that actually look at the projector.
  function cullGlancingDecalTris(geom: import("three").BufferGeometry, projDir: import("three").Vector3) {
    const pos = geom.getAttribute("position");
    const nor = geom.getAttribute("normal");
    const uv = geom.getAttribute("uv");
    const keep: number[] = [];
    const n = new THREE.Vector3();
    const v = new THREE.Vector3();
    for (let i = 0; i < nor.count; i += 3) {
      n.set(0, 0, 0);
      for (let k = 0; k < 3; k++) n.add(v.fromBufferAttribute(nor, i + k));
      if (n.normalize().dot(projDir) > 0.35) keep.push(i);
    }
    if (keep.length * 3 === nor.count) return geom;
    const p = new Float32Array(keep.length * 9);
    const nn = new Float32Array(keep.length * 9);
    const u = new Float32Array(keep.length * 6);
    keep.forEach((tri, j) => {
      for (let k = 0; k < 3; k++) {
        const src = tri + k;
        p.set([pos.getX(src), pos.getY(src), pos.getZ(src)], j * 9 + k * 3);
        nn.set([nor.getX(src), nor.getY(src), nor.getZ(src)], j * 9 + k * 3);
        u.set([uv.getX(src), uv.getY(src)], j * 6 + k * 2);
      }
    });
    const out = new THREE.BufferGeometry();
    out.setAttribute("position", new THREE.BufferAttribute(p, 3));
    out.setAttribute("normal", new THREE.BufferAttribute(nn, 3));
    out.setAttribute("uv", new THREE.BufferAttribute(u, 2));
    geom.dispose();
    return out;
  }

  // ---- Sticker scratch wear ----------------------------------------------------
  // An APPROXIMATION of what CS2 does at "sticker slot N wear" > 0. The game
  // erodes the sticker with a real scratch mask we haven't extracted; this
  // stands in with hash noise so the slider has visible meaning in the viewer.
  // Do not treat it as ground truth — the inspect link is the accurate preview.
  //
  // Patched into the standard material rather than baked into the bitmap:
  // loadTexture() caches by URL, so two slots wearing the same sticker at
  // different wear would fight over one cached texture.
  function applyStickerWear(mat: import("three").MeshStandardMaterial, wear: number) {
    if (wear <= 0) return; // exact no-op at pristine
    mat.onBeforeCompile = (shader) => {
      shader.uniforms.uStickerWear = { value: wear };
      shader.fragmentShader = shader.fragmentShader
        .replace(
          "#include <common>",
          `#include <common>
           uniform float uStickerWear;
           float scratchHash(vec2 p) {
             return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
           }
           // Value noise: cheap, and smooth enough to read as flaking rather
           // than as per-pixel static.
           float scratchNoise(vec2 p) {
             vec2 i = floor(p), f = fract(p);
             f = f * f * (3.0 - 2.0 * f);
             return mix(mix(scratchHash(i), scratchHash(i + vec2(1.0, 0.0)), f.x),
                        mix(scratchHash(i + vec2(0.0, 1.0)), scratchHash(i + vec2(1.0, 1.0)), f.x), f.y);
           }`,
        )
        .replace(
          "#include <map_fragment>",
          `#include <map_fragment>
           {
             // Two octaves: broad patches peel first, fine grain frays the rest.
             float n = scratchNoise(vMapUv * 34.0) * 0.65 + scratchNoise(vMapUv * 96.0) * 0.35;
             // Edges give up before the middle does, like a real peeling decal.
             float edge = 1.0 - 2.0 * max(abs(vMapUv.x - 0.5), abs(vMapUv.y - 0.5));
             n = clamp(n * (0.55 + 0.45 * edge), 0.0, 1.0);
             // Soft threshold so the boundary frays instead of hard-cutting.
             diffuseColor.a *= smoothstep(uStickerWear - 0.12, uStickerWear + 0.12, n);
             // Survivors fade and grey out as they scuff up.
             diffuseColor.rgb = mix(diffuseColor.rgb, vec3(dot(diffuseColor.rgb, vec3(0.299, 0.587, 0.114))), uStickerWear * 0.45);
             diffuseColor.rgb *= 1.0 - uStickerWear * 0.25;
           }`,
        );
    };
    // Materials are cached by program; without this the patched shader can be
    // skipped in favour of an already-compiled unpatched one.
    mat.customProgramCacheKey = () => `stickerWear:${wear.toFixed(3)}`;
  }

  async function buildDecal(st: StickerPlacement) {
    const key = JSON.stringify([st.image, st.x, st.y, st.r, st.w]);
    const prev = decals.get(st.slot);
    if (prev?.key === key) return;
    // First decal for this slot = the user just added it. Flash it so they can
    // find it on a busy finish. Re-drags/edits rebuild silently.
    const isNew = !prev;
    const seq = ++decalSeq;
    decals.set(st.slot, { key, seq });
    const tex = await loadTexture(st.image).catch(() => null);
    if (disposed || !tex) return;
    const current = decals.get(st.slot);
    if (!current || current.seq > seq || current.key !== key) return; // superseded
    // Real anchor when we have the model's markup; the old silhouette guess
    // only as a fallback for weapons we couldn't fetch markup for.
    const mk = slotMarkup(st.slot);
    let hit: { mesh: import("three").Mesh; point: import("three").Vector3; normal: import("three").Vector3 } | null;
    if (mk) {
      hit = uv1ToSurface(
        mk.offset[0] + clamp(st.x ?? 0, bounds.x[0], bounds.x[1]) + 0.5,
        mk.offset[1] + clamp(st.y ?? 0, bounds.y[0], bounds.y[1]) + 0.5,
      );
    } else {
      const l = slotBaseL(st.slot) + clamp(st.x ?? 0, bounds.x[0], bounds.x[1]) * OFFSET_SCALE;
      const h = baseH + clamp(st.y ?? 0, bounds.y[0], bounds.y[1]) * OFFSET_SCALE;
      hit = castAt(l, h);
    }
    if (!hit) return;
    disposeSlotMesh(st.slot);
    const orient = new THREE.Object3D();
    orient.position.copy(hit.point);
    orient.lookAt(hit.point.clone().add(hit.normal));
    orient.rotation.z += ((st.r ?? 0) * Math.PI) / 180;
    // Shallow projection depth: deep boxes capture geometry LAYERS above the
    // surface (the rail over the receiver) and paste the sticker onto them.
    const size = decalSizeFor(st.slot);
    const raw = new DecalGeometry(hit.mesh, hit.point, orient.rotation, new THREE.Vector3(size, size, size * 0.35));
    const geom = cullGlancingDecalTris(raw, hit.normal);
    const mat = new THREE.MeshStandardMaterial({
      map: tex,
      transparent: true,
      depthWrite: false,
      polygonOffset: true,
      // Factor scales with depth slope — a big factor on steep triangles
      // yanks the decal in front of everything (it showed through the rail).
      polygonOffsetFactor: -1,
      polygonOffsetUnits: -2,
      roughness: 0.55,
      metalness: 0,
    });
    applyStickerWear(mat, st.w ?? 0);
    const mesh = new THREE.Mesh(geom, mat);
    mesh.userData.stickerSlot = st.slot;
    mesh.renderOrder = 10 + st.slot;
    scene.add(mesh);
    liveMesh.set(st.slot, mesh);
    if (isNew) flashSticker(st.slot);
  }

  // ---- "It's over here" flash --------------------------------------------------
  // Pulses the decal's emissive so a newly placed sticker announces itself even
  // against a loud paint. Purely visual: never touches the saved placement, and
  // always resets emissive to black so it can't leave a decal glowing.
  const FLASH_MS = 1100;
  const flashing = new Map<number, number>(); // slot -> start timestamp
  function flashSticker(slot: number) {
    if (!liveMesh.has(slot)) return;
    flashing.set(slot, performance.now());
  }
  function stepFlashes(now: number) {
    for (const [slot, start] of [...flashing]) {
      const mesh = liveMesh.get(slot);
      const mat = mesh?.material as import("three").MeshStandardMaterial | undefined;
      if (!mat?.emissive) {
        flashing.delete(slot);
        continue;
      }
      const t = (now - start) / FLASH_MS;
      if (t >= 1) {
        mat.emissive.setScalar(0);
        mat.emissiveIntensity = 1;
        flashing.delete(slot);
        continue;
      }
      // Three quick pulses that fade out over the flash's life.
      const pulse = Math.abs(Math.sin(t * Math.PI * 3)) * (1 - t);
      mat.emissive.setScalar(1);
      mat.emissiveIntensity = pulse * 0.9;
    }
  }

  function setStickers(stickers: StickerPlacement[]) {
    if (disposed) return;
    const wanted = new Set(stickers.map((s) => s.slot));
    for (const slot of [...decals.keys()]) {
      if (!wanted.has(slot)) removeDecal(slot);
    }
    stickers.forEach((st) => void buildDecal(st));
  }

  // ---- Charm: verlet pendulum hanging off the body -----------------------------
  const CORD_LEN = sizeL * 0.012;
  const GRAVITY = sizeL * 7;
  type Charm = {
    sprite: import("three").Sprite;
    line: import("three").Mesh;
    pivot: import("three").Vector3;
    pos: import("three").Vector3;
    prev: import("three").Vector3;
    key: string;
    cy: number;
    cz: number;
    w: number; // sprite base scale (aspect-correct, from cropped art)
    h: number;
  };
  let charm: Charm | null = null;

  function removeCharm() {
    if (!charm) return;
    scene.remove(charm.sprite);
    scene.remove(charm.line);
    charm.sprite.material.dispose();
    charm.line.geometry.dispose();
    (charm.line.material as import("three").Material).dispose();
    charm = null;
  }

  // Cast upward from below the body to find the ACTUAL underside surface at
  // this point along the weapon — the charm clips onto the gun, not into air.
  function castUnderside(l: number, sOff: number) {
    // A single ray can slip through gaps (trigger guard, mag well) — scan a
    // small neighborhood and take the first real surface hit.
    for (const dl of [0, 0.02, -0.02, 0.05, -0.05]) {
      for (const ds of [0, 0.08, -0.08, 0.18, -0.18]) {
        const origin = new THREE.Vector3();
        origin.setComponent(AXIS_L, l + dl * sizeL);
        origin.setComponent(AXIS_H, cbox.min.getComponent(AXIS_H) - sizeH);
        origin.setComponent(AXIS_S, centerS + sOff + ds * sizeS);
        const dir = new THREE.Vector3();
        dir.setComponent(AXIS_H, 1);
        raycaster.set(origin, dir);
        const hit = raycaster.intersectObjects(weaponMeshes, false)[0];
        if (hit) return hit;
      }
    }
    return null;
  }
  const centerH = (cbox.min.getComponent(AXIS_H) + cbox.max.getComponent(AXIS_H)) / 2;

  // THE anchor: where CS2 itself hangs a charm on this weapon, read from the
  // model's own `keychain` attachment (see scripts/extract-models.sh §3c).
  // It is hand-placed per weapon and no geometric rule reproduces it — the
  // AK's sits forward of the ejection port while the M4A4's sits behind it.
  //
  // CS2 *does* honour keychain offset_x/y/z on inspect links; the earlier
  // "it ignores them" reading was our own encoder bug (offsets were written as
  // varints where the Sticker message declares `optional float`, so the game
  // dropped them and fell back to the attachment). See backend/src/inspect.ts.
  //
  // Stored in the pre-centering model frame; `center` is subtracted because
  // mountViewer recenters the object on the origin before this runs.
  // Charm offsets travel to the game as Source inches in the weapon's model
  // frame (x forward/muzzle, y left, z up). The GLB is that frame swizzled and
  // scaled, so the conversion both ways is the node matrix's permutation.
  const SRC_TO_M = 0.0254;
  const offsetToWorld = (c: { x?: number | null; y?: number | null; z?: number | null }) =>
    new THREE.Vector3((c.y ?? 0) * SRC_TO_M, (c.z ?? 0) * SRC_TO_M, (c.x ?? 0) * SRC_TO_M);
  const worldToOffset = (v: import("three").Vector3) => ({
    x: v.z / SRC_TO_M,
    y: v.x / SRC_TO_M,
    z: v.y / SRC_TO_M,
  });

  const charmAnchor = (() => {
    const a = (CHARM_ANCHORS as Record<string, { keychain: number[] } | undefined>)[model];
    if (!a || a.keychain.length !== 3) return null;
    return new THREE.Vector3(a.keychain[0], a.keychain[1], a.keychain[2]).sub(center);
  })();

  // The anchor CS2 gives us is a clip point, which on some weapons sits just
  // inside the shell — hang from it verbatim and the charm renders half-buried
  // or pops through as the body rotates. Cast outward along each axis; if we
  // exit through the back of a face we started inside, so lift to that surface.
  // RENDER ONLY: the offsets we store and transmit are never touched, so this
  // cannot desync the preview from the game.
  function liftOutOfBody(p: import("three").Vector3) {
    const probe = sizeL * 0.05;
    let best: { point: import("three").Vector3; dist: number } | null = null;
    for (const [ax, sign] of [[AXIS_S, 1], [AXIS_S, -1], [AXIS_H, -1], [AXIS_H, 1]] as [number, number][]) {
      const dir = new THREE.Vector3();
      dir.setComponent(ax, sign);
      raycaster.set(p, dir);
      raycaster.far = probe;
      const hit = raycaster.intersectObjects(weaponMeshes, false)[0];
      raycaster.far = Infinity;
      if (!hit?.face) continue;
      const nrm = hit.face.normal.clone().transformDirection(hit.object.matrixWorld);
      // Exiting through a backface => the start point was inside the shell.
      if (nrm.dot(dir) <= 0) continue;
      if (!best || hit.distance < best.dist) {
        best = { point: hit.point.clone().addScaledVector(nrm, sizeL * 0.004), dist: hit.distance };
      }
    }
    return best ? best.point : p;
  }

  function charmPivot(c: CharmPlacement) {
    // Keychain offsets are ABSOLUTE positions in the weapon's model space, in
    // Source inches — not deltas from the attachment. (Sending zeros drops the
    // charm at the model origin near the grip, which is what settled it.) With
    // no offsets set the game falls back to the `keychain` attachment, so that
    // is what an unplaced charm previews at.
    if (charmAnchor) {
      const placed = c.x != null || c.y != null || c.z != null;
      return liftOutOfBody(placed ? offsetToWorld(c).sub(center) : charmAnchor.clone());
    }
    const t = clamp(0.55 + (c.x ?? 0) * 0.35, 0.05, 0.95);
    const l = cbox.min.getComponent(AXIS_L) + t * sizeL;
    // y (when set) is a real anchor height — reattach at that spot on the
    // surface via a side ray; fall back to the underside, then to a formula.
    if (c.y != null && c.y !== 0) {
      const h = centerH + clamp(c.y, -1.2, 1.2) * sizeH * 0.5;
      const side = castAt(l, h);
      if (side) return side.point.clone().addScaledVector(side.normal, sizeL * 0.003);
    }
    let hit = castUnderside(l, (c.z ?? 0) * sizeS * 0.5);
    // Nothing under this exact spot (past the muzzle, inside an opening):
    // walk outward along the body until real geometry is found. A formula
    // pivot here is how charms ended up hanging in empty air.
    for (let step = 1; step <= 10 && !hit; step++) {
      const off = Math.ceil(step / 2) * 0.06 * sizeL * (step % 2 ? 1 : -1);
      hit = castUnderside(l + off, (c.z ?? 0) * sizeS * 0.5);
    }
    if (hit?.face) {
      const nrm = hit.face.normal.clone().transformDirection(hit.object.matrixWorld);
      return hit.point.clone().addScaledVector(nrm, sizeL * 0.003);
    }
    if (hit) return hit.point.clone();
    const pivot = new THREE.Vector3();
    pivot.setComponent(AXIS_L, l);
    pivot.setComponent(AXIS_H, cbox.min.getComponent(AXIS_H) + sizeH * 0.15);
    pivot.setComponent(AXIS_S, centerS + (c.z ?? 0) * sizeS * 0.5);
    return pivot;
  }
  // White ring marking the attachment point — bright while dragging so you
  // can SEE where the charm will clip before you drop it.
  const ringMat = new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0, side: THREE.DoubleSide, depthTest: false });
  const ring = new THREE.Mesh(new THREE.RingGeometry(sizeL * 0.014, sizeL * 0.02, 24), ringMat);
  ring.renderOrder = 30;
  ring.visible = false;
  scene.add(ring);
  function updateRing() {
    if (!charm) {
      ring.visible = false;
      return;
    }
    ring.visible = charmDragging;
    if (!ring.visible) return;
    ring.position.copy(charm.pivot);
    ring.quaternion.copy(camera.quaternion); // face the viewer
    ringMat.opacity = 0.95;
    ring.scale.setScalar(1 + 0.18 * Math.sin(clock.getElapsedTime() * 8));
  }

  async function setCharm(c: CharmPlacement | null) {
    if (disposed) return;
    if (!c) {
      removeCharm();
      return;
    }
    const key = JSON.stringify([c.image, c.x, c.y, c.z]);
    if (charm?.key === key) return;
    if (charm && charm.key.startsWith(JSON.stringify([c.image]).slice(0, -1))) {
      // Same charm, new anchor: move the pivot and let physics swing it there.
      wakeCharm();
      charm.pivot.copy(charmPivot(c));
      charm.cy = c.y ?? 0;
      charm.cz = c.z ?? 0;
      charm.key = key;
      return;
    }
    const loaded = await loadCharmTexture(c.image).catch(() => null);
    if (disposed || !loaded) return;
    removeCharm();
    const pivot = charmPivot(c);
    const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: loaded.tex, depthTest: true }));
    const ch = sizeL * 0.085;
    const cw = ch * loaded.aspect;
    sprite.scale.set(cw, ch, 1);
    // Hang by the TOP edge of the alpha-cropped art — the charm's own
    // connector — so it sits flush against the anchor, no phantom gap.
    sprite.center.set(0.5, 1);
    const pos = pivot.clone();
    pos.y -= CORD_LEN;
    sprite.position.copy(pos);
    // Thin visible cord between anchor and charm: whenever the charm swings
    // away from the body, an invisible link reads as "floating in mid air".
    const line = new THREE.Mesh(
      new THREE.CylinderGeometry(sizeL * 0.0011, sizeL * 0.0011, 1, 6),
      new THREE.MeshStandardMaterial({ color: 0x15110d, roughness: 0.5, metalness: 0.6 }),
    );
    scene.add(line);
    scene.add(sprite);
    charm = { sprite, line, pivot, pos, prev: pos.clone(), key, cy: c.y ?? 0, cz: c.z ?? 0, w: cw, h: ch };
    // A tiny initial nudge so it arrives swinging.
    charm.prev.x += sizeL * 0.01;
  }

  const clock = new THREE.Clock();
  let charmDragging = false;
  let charmCalm = 0;
  let charmAsleep = false;
  const charmLastResolved = new THREE.Vector3();
  function wakeCharm() {
    charmCalm = 0;
    charmAsleep = false;
  }
  function stepCharm() {
    if (!charm) return;
    // Asleep = fully frozen. A resting charm must be pixel-still — micro
    // physics against the gun surface reads as jitter. Woken by drag/flick
    // or a pivot change.
    if (charmAsleep && !charmDragging) {
      updateCharmVisuals();
      return;
    }
    const t = clock.getElapsedTime();
    let contact = false;
    if (!charmDragging) {
      const dt = 1 / 60;
      const damp = 0.985;
      const acc = new THREE.Vector3(0, -GRAVITY, 0);
      // Faint breeze ONLY while clearly airborne — near the gun it just
      // injects energy the collision has to fight.
      if (charmCalm < 6) {
        acc.x += Math.sin(t * 1.3) * GRAVITY * 0.005;
        acc.z += Math.cos(t * 0.8) * GRAVITY * 0.004;
      }
      const next = charm.pos
        .clone()
        .add(charm.pos.clone().sub(charm.prev).multiplyScalar(damp))
        .add(acc.multiplyScalar(dt * dt));
      charm.prev.copy(charm.pos);
      charm.pos.copy(next);
      // Velocity clamp — runaway energy can never build up.
      const vel = charm.pos.clone().sub(charm.prev);
      const vmax = sizeL * 0.012;
      if (vel.length() > vmax) {
        charm.pos.copy(charm.prev.clone().add(vel.normalize().multiplyScalar(vmax)));
      }
    }
    // Collision FIRST, cord clamp LAST. The old order (cord, then push-out)
    // left each frame ending on a pushed-out position the next frame's cord
    // clamp snapped back — the charm visibly flickered between the two spots.
    // With the cord as the final authority every frame resolves to the same
    // point, so contact is stable and sleep can latch.
    {
      const rC = sizeL * 0.03;
      // Test from the sprite's visual CENTER (pos is the hang point at the
      // art's top edge), and never push along the cord — the anchor surface
      // is supposed to be right there, it isn't a penetration.
      const cpos = charm.pos.clone();
      cpos.y -= charm.h * 0.5;
      const toPivot = charm.pivot.clone().sub(cpos).normalize();
      let best: { nrm: import("three").Vector3; depth: number } | null = null;
      for (const [ax, sign] of [[AXIS_S, 1], [AXIS_S, -1], [AXIS_L, 1], [AXIS_L, -1], [AXIS_H, 1], [AXIS_H, -1]] as [number, number][]) {
        const d = new THREE.Vector3();
        d.setComponent(ax, sign);
        if (d.dot(toPivot) > 0.6) continue;
        raycaster.set(cpos, d);
        raycaster.far = rC;
        const hit = raycaster.intersectObjects(weaponMeshes, false)[0];
        if (hit?.face) {
          // The real keychain anchor is a clip point ON the body, so the
          // surface right next to it is not a penetration — pushing off it
          // fights the cord clamp forever and the charm buzzes instead of
          // settling. Only geometry beyond the cord's reach can be a real
          // collision.
          if (hit.point.distanceTo(charm.pivot) < CORD_LEN * 1.2) continue;
          const depth = rC - hit.distance;
          if (!best || depth > best.depth) {
            best = { nrm: hit.face.normal.clone().transformDirection(hit.object.matrixWorld), depth };
          }
        }
      }
      raycaster.far = Infinity;
      if (best) {
        contact = true;
        charm.pos.add(best.nrm.multiplyScalar(best.depth * 0.35)); // soft push
        charm.prev.lerp(charm.pos, 0.85); // contact kills most velocity
      }
    }
    // Cord constraint (taut only — it can hang slack while dragged upward).
    const dir = charm.pos.clone().sub(charm.pivot);
    const len = dir.length();
    if (len > CORD_LEN && !charmDragging) {
      charm.pos.copy(charm.pivot.clone().add(dir.multiplyScalar(CORD_LEN / len)));
    }
    // Settle detection → sleep. Measured against the last FULLY RESOLVED
    // position, not charm.prev: collision mutates prev mid-frame, so comparing
    // to it reports the cord clamp's correction every frame and a charm that
    // has actually converged never looks calm enough to sleep.
    if (!charmDragging) {
      const speed = charm.pos.distanceTo(charmLastResolved);
      if (speed < sizeL * 0.001) charmCalm += contact ? 3 : 1;
      else charmCalm = 0;
      if (charmCalm > 30) {
        charmAsleep = true;
        charm.prev.copy(charm.pos);
      }
    }
    charmLastResolved.copy(charm.pos);
    updateCharmVisuals();
  }
  function updateCharmVisuals() {
    if (!charm) return;
    charm.sprite.position.copy(charm.pos);
    // Stretch the chain cylinder between pivot and bob. Only show it while
    // the charm is actually away from its anchor (dragging/swinging) — at
    // rest the art's own clasp sits at the anchor and a leftover cord stub
    // reads as a floating black bar.
    const mid = charm.pivot.clone().add(charm.pos).multiplyScalar(0.5);
    const span = charm.pos.clone().sub(charm.pivot);
    charm.line.visible = !charmAsleep && span.length() > CORD_LEN * 1.2;
    charm.line.position.copy(mid);
    charm.line.scale.set(1, Math.max(span.length(), 1e-5), 1);
    charm.line.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), span.clone().normalize());
  }

  // ---- Interactive placement ---------------------------------------------------
  const el = renderer.domElement;
  let drag: { type: "sticker"; slot: number } | { type: "charm" } | null = null;
  let rotateAnchorX = 0;
  let rotateStartDeg = 0;
  let lastCharmX: number | null = null;
  let lastCharmY: number | null = null;
  let lastCharmZ: number | null = null;
  const dragVel = new THREE.Vector3();
  const dragPrev = new THREE.Vector3();
  const pointerNdc = new THREE.Vector2();
  function updatePointer(e: PointerEvent) {
    const rect = el.getBoundingClientRect();
    pointerNdc.set(((e.clientX - rect.left) / rect.width) * 2 - 1, -((e.clientY - rect.top) / rect.height) * 2 + 1);
  }

  function onPointerDown(e: PointerEvent) {
    if (!opts?.interactive || e.button !== 0) return;
    updatePointer(e);
    raycaster.setFromCamera(pointerNdc, camera);
    if (charm) {
      const hitCharm = raycaster.intersectObject(charm.sprite, false)[0];
      if (hitCharm) {
        drag = { type: "charm" };
        wakeCharm();
        charmDragging = true;
        dragPrev.set(0, 0, 0);
        dragVel.set(0, 0, 0);
        charm.sprite.scale.set(charm.w * 1.18, charm.h * 1.18, 1); // picked up — reads as grabbed
        controls.enabled = false;
        el.setPointerCapture(e.pointerId);
        return;
      }
    }
    const decalMeshes = [...liveMesh.values()];
    const hit = raycaster.intersectObjects(decalMeshes, false)[0];
    if (hit) {
      drag = { type: "sticker", slot: (hit.object.userData.stickerSlot as number) ?? 0 };
      // Shift turns the same drag into a rotate — no extra handle to hit, and
      // it can be decided mid-gesture. Anchor the sweep where the press landed.
      rotateAnchorX = e.clientX;
      const cur = decals.get(drag.slot);
      rotateStartDeg = cur ? (JSON.parse(cur.key) as [string, number | null, number | null, number | null])[3] ?? 0 : 0;
      controls.enabled = false;
      el.setPointerCapture(e.pointerId);
    }
  }

  function onPointerMove(e: PointerEvent) {
    if (!drag) return;
    updatePointer(e);
    raycaster.setFromCamera(pointerNdc, camera);
    if (drag.type === "sticker") {
      const entryNow = decals.get(drag.slot);
      if (e.shiftKey && entryNow) {
        // ROTATE: horizontal sweep -> degrees. Half a degree per pixel is fine
        // for the eye and lands on the 0.5 steps the game quantizes to anyway.
        const parsed = JSON.parse(entryNow.key) as [string, number | null, number | null, number | null, number | null];
        const deg = round(((rotateStartDeg + (e.clientX - rotateAnchorX) * 0.5) % 360 + 360) % 360, 1);
        if (parsed[3] === deg) return;
        void buildDecal({ slot: drag.slot, image: parsed[0], x: parsed[1], y: parsed[2], r: deg, w: parsed[4] });
        opts?.onStickerRotated?.(drag.slot, deg);
        return;
      }
      const hit = raycaster.intersectObjects(weaponMeshes, false)[0];
      if (!hit) return;
      // Report the drag in the game's space: read the surface UV1 under the
      // pointer and subtract the slot's own anchor. The old version measured
      // against an invented base along the body, so the numbers we stored
      // meant nothing to the game.
      const mk = slotMarkup(drag.slot);
      let gx: number, gy: number;
      const uv = mk ? surfaceUv1(hit) : null;
      if (mk && uv) {
        gx = round(clamp(uv.u - 0.5 - mk.offset[0], bounds.x[0], bounds.x[1]), 4);
        gy = round(clamp(uv.v - 0.5 - mk.offset[1], bounds.y[0], bounds.y[1]), 4);
      } else {
        gx = round(clamp((hit.point.getComponent(AXIS_L) - slotBaseL(drag.slot)) / OFFSET_SCALE, bounds.x[0], bounds.x[1]), 3);
        gy = round(clamp((hit.point.getComponent(AXIS_H) - baseH) / OFFSET_SCALE, bounds.y[0], bounds.y[1]), 3);
      }
      const entry = decals.get(drag.slot);
      if (entry) {
        const parsed = JSON.parse(entry.key) as [string, number | null, number | null, number | null, number | null];
        if (parsed[1] === gx && parsed[2] === gy) return;
        void buildDecal({ slot: drag.slot, image: parsed[0], x: gx, y: gy, r: parsed[3], w: parsed[4] });
        opts?.onStickerPlaced?.(drag.slot, gx, gy);
      }
    } else if (charm) {
      // Dragging moves the ATTACHMENT POINT along the body — the charm keeps
      // previewing its true final hang (anchored, chain taut) the whole time,
      // so where you see it is exactly where it stays when you drop it.
      const planeNormal = camera.getWorldDirection(new THREE.Vector3()).negate();
      const plane = new THREE.Plane().setFromNormalAndCoplanarPoint(planeNormal, charm.pivot);
      // Anchor ANYWHERE on the weapon: raycast the surface under the pointer
      // (side, top, grip — wherever). Off the model, slide along the body via
      // the camera plane instead.
      const surf = raycaster.intersectObjects(weaponMeshes, false)[0];
      let anchor: import("three").Vector3 | null = null;
      if (surf?.face) {
        const nrm = surf.face.normal.clone().transformDirection(surf.object.matrixWorld);
        anchor = surf.point.clone().addScaledVector(nrm, sizeL * 0.003);
      } else if (surf) {
        anchor = surf.point.clone();
      } else {
        const p = raycaster.ray.intersectPlane(plane, new THREE.Vector3());
        if (!p) return;
        dragVel.copy(p).sub(dragPrev.lengthSq() ? dragPrev : p);
        dragPrev.copy(p);
        const tl = (p.getComponent(AXIS_L) - cbox.min.getComponent(AXIS_L)) / sizeL;
        anchor = charmPivot({ image: "", x: round(clamp((tl - 0.55) / 0.35, -1, 1), 2), y: null, z: null });
      }
      if (surf) {
        dragVel.copy(anchor).sub(dragPrev.lengthSq() ? dragPrev : anchor);
        dragPrev.copy(anchor);
      }
      charm.pivot.copy(anchor);
      // Where we know the real attachment, report the drag as an offset FROM
      // it in the game's own units, so the number we store is the number the
      // inspect link carries. Without an anchor there is nothing to be
      // relative to, so fall back to the old normalised body fractions.
      // All THREE components must be reported. The offset frame is Source's
      // (x = along the weapon, y = lateral, z = vertical), so dragging up and
      // down moves z — send only (x, y) and vertical drags are silently
      // dropped, which reads as "the charm can only move horizontally".
      let x: number, y: number, z: number;
      if (charmAnchor) {
        // Absolute, to match what the game consumes — undo the recentering to
        // get back into model space rather than measuring from the anchor.
        const off = worldToOffset(anchor.clone().add(center));
        x = round(off.x, 3);
        y = round(off.y, 3);
        z = round(off.z, 3);
        charm.cy = y;
        charm.cz = z;
      } else {
        const t = (anchor.getComponent(AXIS_L) - cbox.min.getComponent(AXIS_L)) / sizeL;
        x = round(clamp((t - 0.55) / 0.35, -1, 1), 2);
        y = round(clamp((anchor.getComponent(AXIS_H) - centerH) / (sizeH * 0.5), -1.2, 1.2), 2);
        z = round(clamp((anchor.getComponent(AXIS_S) - centerS) / (sizeS * 0.5), -1.2, 1.2), 2);
        charm.cy = y;
        charm.cz = z;
      }
      const rest = charm.pivot.clone();
      rest.y -= CORD_LEN;
      charm.pos.lerp(rest, 0.4); // glides to each new anchor — no teleporting
      charm.prev.copy(charm.pos);
      if (x !== lastCharmX || y !== lastCharmY || z !== lastCharmZ) {
        lastCharmX = x;
        lastCharmY = y;
        lastCharmZ = z;
        opts?.onCharmPlaced?.(x, y, z);
      }
    }
  }

  function onPointerUp(e: PointerEvent) {
    if (!drag) return;
    if (drag.type === "charm" && charm) {
      charm.sprite.scale.set(charm.w, charm.h, 1);
      // Release kick from your last pointer motion — it lands with a natural
      // little swing instead of freezing (or teleporting).
      wakeCharm();
      const kick = Math.min(dragVel.length(), sizeL * 0.03);
      if (kick > 0) {
        charm.prev.copy(charm.pos).sub(dragVel.clone().normalize().multiplyScalar(kick));
      }
    }
    drag = null;
    charmDragging = false;
    controls.enabled = true;
    try {
      el.releasePointerCapture(e.pointerId);
    } catch {
      /* capture already released */
    }
  }

  // ---- Cursor ------------------------------------------------------------------
  // The viewer runs five gestures off one surface (orbit, pan, zoom, drag a
  // sticker, grab the charm) and the OS cursor set can express about two of
  // them, so the native cursor is hidden and a reticle drawn instead. It reads
  // the SAME raycast the drag handlers do, so what it shows is exactly what a
  // press would grab — a hover that lies is worse than no hover at all.
  // Gated on `still`, NOT on `interactive`: orbit/pan/zoom exist in every
  // on-screen viewer, and only the sticker/charm hover states need placement to
  // be enabled. `still` viewers are offscreen snapshot rigs with no user at all.
  const cursor = opts?.still ? null : createViewerCursor(container, el);
  let orbiting = false;
  let panning = false;
  let shiftHeld = false;
  let hoverKind: "sticker" | "charm" | null = null;
  let hoverRaf = 0;

  function paintCursor() {
    if (!cursor) return;
    let mode: CursorMode;
    if (drag) mode = "grab";
    else if (panning) mode = "pan";
    else if (orbiting) mode = "orbit";
    else if (hoverKind === "sticker") mode = shiftHeld ? "rotate" : "sticker";
    else if (hoverKind === "charm") mode = "charm";
    else mode = "idle";
    cursor.set(mode);
  }

  function onCursorDown(e: PointerEvent) {
    shiftHeld = e.shiftKey;
    // onPointerDown runs first and claims the press if it hit an attachment;
    // whatever is left is an orbit (left) or a pan (middle/right).
    if (!drag) {
      if (e.button === 0) orbiting = true;
      else panning = true;
    }
    paintCursor();
  }

  function onCursorMove(e: PointerEvent) {
    cursor?.move(e.clientX, e.clientY);
    shiftHeld = e.shiftKey;
    if (drag || orbiting || panning) {
      paintCursor();
      return;
    }
    // Nothing is grabbable without placement, so skip the raycast entirely —
    // a view-only viewer never leaves the orbit/pan/zoom states.
    if (!opts?.interactive) {
      paintCursor();
      return;
    }
    // Hover resolves at most once per frame — pointermove outruns the display
    // and every resolve is a raycast.
    if (hoverRaf) return;
    hoverRaf = requestAnimationFrame(() => {
      hoverRaf = 0;
      if (disposed || drag) return;
      updatePointer(e);
      raycaster.setFromCamera(pointerNdc, camera);
      hoverKind =
        charm && raycaster.intersectObject(charm.sprite, false)[0]
          ? "charm"
          : raycaster.intersectObjects([...liveMesh.values()], false)[0]
            ? "sticker"
            : null;
      paintCursor();
    });
  }

  function onCursorUp() {
    orbiting = false;
    panning = false;
    paintCursor();
  }
  function onCursorEnter(e: PointerEvent) {
    cursor?.move(e.clientX, e.clientY);
    cursor?.show(true);
  }
  function onCursorLeave() {
    cursor?.show(false);
    orbiting = false;
    panning = false;
    hoverKind = null;
  }
  function onCursorWheel() {
    cursor?.set("zoom");
  }
  // Shift retargets a sticker drag from move to rotate, so the reticle has to
  // follow the modifier even when the pointer is perfectly still.
  function onCursorKey(e: KeyboardEvent) {
    if (e.key !== "Shift") return;
    shiftHeld = e.type === "keydown";
    paintCursor();
  }

  if (opts?.interactive) {
    el.addEventListener("pointerdown", onPointerDown);
    el.addEventListener("pointermove", onPointerMove);
    el.addEventListener("pointerup", onPointerUp);
    el.addEventListener("pointercancel", onPointerUp);
  }

  if (cursor) {
    el.addEventListener("pointerdown", onCursorDown);
    el.addEventListener("pointermove", onCursorMove);
    el.addEventListener("pointerenter", onCursorEnter);
    el.addEventListener("pointerleave", onCursorLeave);
    el.addEventListener("wheel", onCursorWheel, { passive: true });
    // Releases land wherever the pointer ended up — OrbitControls captures to
    // its own target, so a listener on the canvas would miss half of them.
    window.addEventListener("pointerup", onCursorUp);
    window.addEventListener("pointercancel", onCursorUp);
    window.addEventListener("keydown", onCursorKey);
    window.addEventListener("keyup", onCursorKey);
  }

  // Initial attachments.
  setStickers(opts?.stickers ?? []);
  void setCharm(opts?.charm ?? null);

  let raf = 0;
  const renderLoop = () => {
    if (disposed) return;
    controls.update();
    stepCharm();
    updateRing();
    stepFlashes(performance.now());
    renderer.render(scene, camera);
    raf = requestAnimationFrame(renderLoop);
  };

  // Physics-only sibling of renderLoop for offscreen/still viewers.
  const settleLoop = () => {
    if (disposed) return;
    stepCharm();
    raf = requestAnimationFrame(settleLoop);
  };

  const resize = () => {
    const w = container.clientWidth || 1;
    const h = container.clientHeight || 1;
    renderer.setSize(w, h, false);
    camera.aspect = w / h;
    camera.updateProjectionMatrix();
  };
  // If the browser drops our context (mobile Safari sheds the oldest one when
  // too many are live), the rAF loop would otherwise keep calling render() on a
  // dead context every frame and flood the console with GL errors. Stop cleanly
  // instead and let the caller decide whether to remount.
  const onContextLost = (e: Event) => {
    e.preventDefault();
    disposed = true;
    cancelAnimationFrame(raf);
    opts?.onContextLost?.();
  };
  renderer.domElement.addEventListener("webglcontextlost", onContextLost);

  const observer = new ResizeObserver(resize);
  observer.observe(container);
  resize();
  // A still viewer exists only to be snapshot()'d, and snapshot() renders its
  // own fresh frame — so drive the charm's verlet settle (which genuinely needs
  // the frames) without paying for a full PBR draw each tick. During a bake
  // sweep that's the difference between one GPU-bound scene and N of them.
  if (opts?.still) settleLoop();
  else renderLoop();

  return {
    setStickers,
    flashSticker,
    setCharm: (c) => void setCharm(c),
    // Render one fresh frame and hand back a PNG of exactly what's on screen.
    async snapshot() {
      if (disposed) return null;
      controls.update();
      stepCharm();
      renderer.render(scene, camera);
      return await new Promise<Blob | null>((resolve) => renderer.domElement.toBlob(resolve, "image/png"));
    },
    dispose() {
      disposed = true;
      cancelAnimationFrame(raf);
      observer.disconnect();
      renderer.domElement.removeEventListener("webglcontextlost", onContextLost);
      if (opts?.interactive) {
        el.removeEventListener("pointerdown", onPointerDown);
        el.removeEventListener("pointermove", onPointerMove);
        el.removeEventListener("pointerup", onPointerUp);
        el.removeEventListener("pointercancel", onPointerUp);
      }
      if (cursor) {
        el.removeEventListener("pointerdown", onCursorDown);
        el.removeEventListener("pointermove", onCursorMove);
        el.removeEventListener("pointerenter", onCursorEnter);
        el.removeEventListener("pointerleave", onCursorLeave);
        el.removeEventListener("wheel", onCursorWheel);
        window.removeEventListener("pointerup", onCursorUp);
        window.removeEventListener("pointercancel", onCursorUp);
        window.removeEventListener("keydown", onCursorKey);
        window.removeEventListener("keyup", onCursorKey);
      }
      cancelAnimationFrame(hoverRaf);
      cursor?.destroy();
      for (const slot of new Set([...decals.keys(), ...liveMesh.keys()])) removeDecal(slot);
      removeCharm();
      ring.geometry.dispose();
      ringMat.dispose();
      controls.dispose();
      releaseComposite?.();
      // This context is about to go — nothing can reuse its composites.
      dropCompositeCache(renderer);
      envTex.dispose();
      // dispose() alone leaves the GL context alive until the canvas is GC'd,
      // which under mobile memory pressure can be a long time — long enough to
      // walk past Safari's live-context cap and have it start killing contexts.
      // forceContextLoss releases it now; zeroing the canvas drops its backing
      // store rather than waiting on the collector.
      renderer.forceContextLoss();
      renderer.dispose();
      renderer.domElement.remove();
      renderer.domElement.width = 0;
      renderer.domElement.height = 0;
      // Cloned meshes share cached geometry/materials — don't dispose those;
      // the LRU owns their lifetime.
    },
  };
}
